apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-service-config
  namespace: hamkkebu
  labels:
    app: ledger-service-backend
    service: ledger-service
data:
  DB_URL: "jdbc:mysql://hamkkebu-dev-mysql.xxxxxxxxxxxx.ap-northeast-2.rds.amazonaws.com:3306/hamkkebu_ledger?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8"
  KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
  AUTH_SERVICE_GRPC_ADDRESS: "static://auth-service-backend:9091"
