apiVersion: v1
kind: Service
metadata:
  name: ledger-service-backend
  namespace: hamkkebu
  labels:
    app: ledger-service-backend
spec:
  type: ClusterIP
  selector:
    app: ledger-service-backend
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
    - name: grpc
      port: 9093
      targetPort: 9093
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service-backend-nodeport
  namespace: hamkkebu
  labels:
    app: ledger-service-backend
spec:
  type: NodePort
  selector:
    app: ledger-service-backend
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 31082
      protocol: TCP
