apiVersion: v1
kind: Service
metadata:
  name: ledger-service-backend
  labels:
    app: ledger-service-backend
    service: ledger-service
    component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 9092
      targetPort: 9090
      protocol: TCP
  selector:
    app: ledger-service-backend
